export const presetMenuItems = [
  // Bulk Solids / Gravies (kg)
  { name: "Rice", category: "main", unit: "kg" },
  { name: "Jeera Rice", category: "main", unit: "kg" },
  { name: "Veg Pulao", category: "main", unit: "kg" },
  { name: "Peas Pulao", category: "main", unit: "kg" },
  { name: "Veg Biryani", category: "main", unit: "kg" },
  { name: "Chicken Biryani", category: "main", unit: "kg" },
  { name: "Mutton Biryani", category: "main", unit: "kg" },
  { name: "Egg Biryani", category: "main", unit: "kg" },
  { name: "Dal Tadka", category: "main", unit: "kg" },
  { name: "Dal Makhani", category: "main", unit: "kg" },
  { name: "Yellow Dal", category: "main", unit: "kg" },
  { name: "Chana Dal", category: "main", unit: "kg" },
  { name: "Paneer Butter Masala", category: "main", unit: "kg" },
  { name: "Kadhai Paneer", category: "main", unit: "kg" },
  { name: "Palak Paneer", category: "main", unit: "kg" },
  { name: "Shahi Paneer", category: "main", unit: "kg" },
  { name: "Chole", category: "main", unit: "kg" },
  { name: "Rajma", category: "main", unit: "kg" },
  { name: "Mixed Veg", category: "main", unit: "kg" },
  { name: "Aloo Gobi", category: "main", unit: "kg" },
  { name: "Bhindi Masala", category: "main", unit: "kg" },
  { name: "Baingan Bharta", category: "main", unit: "kg" },
  { name: "Malai Kofta", category: "main", unit: "kg" },
  { name: "Butter Chicken", category: "main", unit: "kg" },
  { name: "Chicken Tikka Masala", category: "main", unit: "kg" },
  { name: "Fish Curry", category: "main", unit: "kg" },
  { name: "Mutton Curry", category: "main", unit: "kg" },
  { name: "Egg Curry", category: "main", unit: "kg" },
  { name: "Upma", category: "breakfast", unit: "kg" },
  { name: "Poha", category: "breakfast", unit: "kg" },
  { name: "Khichdi", category: "main", unit: "kg" },
  { name: "Pav Bhaji (Bhaji)", category: "main", unit: "kg" },
  { name: "Chilli Chicken", category: "main", unit: "kg" },
  { name: "Chilli Paneer", category: "main", unit: "kg" },
  { name: "Veg Manchurian", category: "main", unit: "kg" },
  { name: "Hakka Noodles", category: "main", unit: "kg" },
  { name: "Fried Rice", category: "main", unit: "kg" },
  { name: "Pasta", category: "main", unit: "kg" },
  { name: "Macaroni", category: "main", unit: "kg" },

  // Countable Breads (pieces)
  { name: "Roti", category: "bread", unit: "pieces" },
  { name: "Chapati", category: "bread", unit: "pieces" },
  { name: "Phulka", category: "bread", unit: "pieces" },
  { name: "Butter Naan", category: "bread", unit: "pieces" },
  { name: "Garlic Naan", category: "bread", unit: "pieces" },
  { name: "Plain Naan", category: "bread", unit: "pieces" },
  { name: "Tandoori Roti", category: "bread", unit: "pieces" },
  { name: "Aloo Paratha", category: "bread", unit: "pieces" },
  { name: "Paneer Paratha", category: "bread", unit: "pieces" },
  { name: "Gobi Paratha", category: "bread", unit: "pieces" },
  { name: "Lachha Paratha", category: "bread", unit: "pieces" },
  { name: "Puri", category: "bread", unit: "pieces" },
  { name: "Bhatura", category: "bread", unit: "pieces" },
  { name: "Pav", category: "bread", unit: "pieces" },

  // Countable Snacks (pieces)
  { name: "Samosa", category: "snack", unit: "pieces" },
  { name: "Kachori", category: "snack", unit: "pieces" },
  { name: "Vada Pav", category: "snack", unit: "pieces" },
  { name: "Aloo Tikki", category: "snack", unit: "pieces" },
  { name: "Pakora", category: "snack", unit: "pieces" },
  { name: "Bread Pakora", category: "snack", unit: "pieces" },
  { name: "Sandwich", category: "snack", unit: "pieces" },
  { name: "Veg Sandwich", category: "snack", unit: "pieces" },
  { name: "Grilled Sandwich", category: "snack", unit: "pieces" },
  { name: "Burger", category: "snack", unit: "pieces" },
  { name: "Veg Burger", category: "snack", unit: "pieces" },
  { name: "Chicken Burger", category: "snack", unit: "pieces" },
  { name: "Wrap", category: "snack", unit: "pieces" },
  { name: "Roll", category: "snack", unit: "pieces" },
  { name: "Kathi Roll", category: "snack", unit: "pieces" },
  { name: "Spring Roll", category: "snack", unit: "pieces" },
  { name: "Puff", category: "snack", unit: "pieces" },
  { name: "Veg Puff", category: "snack", unit: "pieces" },

  // South Indian Countables (pieces)
  { name: "Idli", category: "south", unit: "pieces" },
  { name: "Medu Vada", category: "south", unit: "pieces" },
  { name: "Plain Dosa", category: "south", unit: "pieces" },
  { name: "Masala Dosa", category: "south", unit: "pieces" },
  { name: "Rava Dosa", category: "south", unit: "pieces" },
  { name: "Uttapam", category: "south", unit: "pieces" },
  { name: "Appam", category: "south", unit: "pieces" },

  // Desserts / Sweets (pieces or cups)
  { name: "Gulab Jamun", category: "dessert", unit: "pieces" },
  { name: "Rasgulla", category: "dessert", unit: "pieces" },
  { name: "Jalebi", category: "dessert", unit: "pieces" },
  { name: "Ladoo", category: "dessert", unit: "pieces" },
  { name: "Barfi", category: "dessert", unit: "pieces" },
  { name: "Kaju Katli", category: "dessert", unit: "pieces" },
  { name: "Brownie", category: "dessert", unit: "pieces" },
  { name: "Pastry", category: "dessert", unit: "pieces" },
  { name: "Cupcake", category: "dessert", unit: "pieces" },
  { name: "Ice Cream", category: "dessert", unit: "cups" },

  // Hot Beverages (cups)
  { name: "Tea", category: "beverage", unit: "cups" },
  { name: "Masala Chai", category: "beverage", unit: "cups" },
  { name: "Green Tea", category: "beverage", unit: "cups" },
  { name: "Coffee", category: "beverage", unit: "cups" },
  { name: "Filter Coffee", category: "beverage", unit: "cups" },
  { name: "Cold Coffee", category: "beverage", unit: "cups" },
  { name: "Hot Chocolate", category: "beverage", unit: "cups" },

  // Cold Beverages / Liquids (litres)
  { name: "Lassi", category: "beverage", unit: "litres" },
  { name: "Sweet Lassi", category: "beverage", unit: "litres" },
  { name: "Mango Lassi", category: "beverage", unit: "litres" },
  { name: "Buttermilk", category: "beverage", unit: "litres" },
  { name: "Chaas", category: "beverage", unit: "litres" },
  { name: "Mojito", category: "beverage", unit: "litres" },
  { name: "Fresh Lime Soda", category: "beverage", unit: "litres" },
  { name: "Lemonade", category: "beverage", unit: "litres" },
  { name: "Orange Juice", category: "beverage", unit: "litres" },
  { name: "Watermelon Juice", category: "beverage", unit: "litres" },
  { name: "Mixed Fruit Juice", category: "beverage", unit: "litres" },
  { name: "Milkshake", category: "beverage", unit: "litres" },
  { name: "Mango Shake", category: "beverage", unit: "litres" },
  { name: "Chocolate Shake", category: "beverage", unit: "litres" },
  { name: "Soda", category: "beverage", unit: "litres" },
  { name: "Soft Drink", category: "beverage", unit: "litres" },
  { name: "Water", category: "beverage", unit: "litres" },
  { name: "Soup", category: "beverage", unit: "litres" },
  { name: "Tomato Soup", category: "beverage", unit: "litres" },
  { name: "Sweet Corn Soup", category: "beverage", unit: "litres" },
  { name: "Manchow Soup", category: "beverage", unit: "litres" }
];
